"""Tests for YAML export of search results."""

from datetime import date, timedelta

import pytest
import yaml

from rtw.models import (
    CabinClass,
    Itinerary,
    Segment,
    SegmentType,
    Ticket,
    TicketType,
)
from rtw.search.exporter import export_itinerary
from rtw.search.models import (
    AvailabilityStatus,
    CandidateItinerary,
    Direction,
    RouteSegment,
    ScoredCandidate,
    SearchQuery,
    SegmentAvailability,
)

FUTURE = date.today() + timedelta(days=60)
FUTURE_END = date.today() + timedelta(days=120)


def _make_query() -> SearchQuery:
    return SearchQuery(
        cities=["LHR", "NRT", "JFK"],
        origin="SYD",
        date_from=FUTURE,
        date_to=FUTURE_END,
        cabin=CabinClass.BUSINESS,
        ticket_type=TicketType.DONE3,
    )


def _make_scored(
    num_segs=3,
    surface_indices=None,
    avail_statuses=None,
) -> ScoredCandidate:
    surface_indices = surface_indices or set()
    segs = []
    route_segs = []
    for i in range(num_segs):
        st = SegmentType.SURFACE if i in surface_indices else SegmentType.STOPOVER
        segs.append(Segment(**{"from": "AAA", "to": "BBB", "carrier": "AA", "type": st.value}))

        avail = None
        if avail_statuses and i < len(avail_statuses):
            avail = SegmentAvailability(
                status=avail_statuses[i],
                price_usd=500.0 if avail_statuses[i] == AvailabilityStatus.AVAILABLE else None,
            )
        route_segs.append(RouteSegment(
            from_airport="AAA", to_airport="BBB", carrier="AA",
            segment_type=st, availability=avail,
        ))

    itin = Itinerary(
        ticket=Ticket(type=TicketType.DONE3, cabin=CabinClass.BUSINESS, origin="SYD"),
        segments=segs,
    )
    cand = CandidateItinerary(
        itinerary=itin, direction=Direction.EASTBOUND, route_segments=route_segs,
    )
    return ScoredCandidate(candidate=cand, composite_score=85.0, rank=1)


class TestExportBasic:
    def test_export_returns_valid_yaml(self):
        scored = _make_scored()
        query = _make_query()
        result = export_itinerary(scored, query)
        # Should be parseable YAML (strip header comments)
        body = "\n".join(
            line for line in result.splitlines()
            if not line.startswith("#")
        )
        data = yaml.safe_load(body)
        assert data is not None
        assert "ticket" in data
        assert "segments" in data

    def test_header_contains_metadata(self):
        scored = _make_scored()
        query = _make_query()
        result = export_itinerary(scored, query)
        assert "# Generated by: rtw search" in result
        assert "# Direction: eastbound" in result
        assert "# Score:" in result
        assert "# Rank:" in result

    def test_segment_count_matches(self):
        scored = _make_scored(num_segs=5)
        query = _make_query()
        result = export_itinerary(scored, query)
        body = "\n".join(line for line in result.splitlines() if not line.startswith("#"))
        data = yaml.safe_load(body)
        assert len(data["segments"]) == 5

    def test_ticket_fields_present(self):
        scored = _make_scored()
        query = _make_query()
        result = export_itinerary(scored, query)
        body = "\n".join(line for line in result.splitlines() if not line.startswith("#"))
        data = yaml.safe_load(body)
        ticket = data["ticket"]
        assert ticket["type"] == "DONE3"
        assert ticket["cabin"] == "business"
        assert ticket["origin"] == "SYD"


class TestExportDates:
    def test_stopovers_get_dates(self):
        scored = _make_scored(num_segs=3)
        query = _make_query()
        result = export_itinerary(scored, query)
        body = "\n".join(line for line in result.splitlines() if not line.startswith("#"))
        data = yaml.safe_load(body)
        for seg in data["segments"]:
            assert "date" in seg

    def test_surface_segments_no_date(self):
        scored = _make_scored(num_segs=3, surface_indices={1})
        query = _make_query()
        result = export_itinerary(scored, query)
        body = "\n".join(line for line in result.splitlines() if not line.startswith("#"))
        data = yaml.safe_load(body)
        # Surface segment should not have a date key (or if present, it's None)
        surface_seg = data["segments"][1]
        assert surface_seg.get("date") is None

    def test_dates_within_range(self):
        scored = _make_scored(num_segs=5)
        query = _make_query()
        result = export_itinerary(scored, query)
        body = "\n".join(line for line in result.splitlines() if not line.startswith("#"))
        data = yaml.safe_load(body)
        for seg in data["segments"]:
            if seg.get("date"):
                d = date.fromisoformat(seg["date"])
                assert d >= query.date_from
                assert d <= query.date_to


class TestExportAvailability:
    def test_availability_notes_included(self):
        scored = _make_scored(
            num_segs=2,
            avail_statuses=[AvailabilityStatus.AVAILABLE, AvailabilityStatus.NOT_AVAILABLE],
        )
        query = _make_query()
        result = export_itinerary(scored, query)
        body = "\n".join(line for line in result.splitlines() if not line.startswith("#"))
        data = yaml.safe_load(body)
        # First segment should have availability note with price
        assert "availability: available" in data["segments"][0].get("notes", "")
        assert "$500" in data["segments"][0].get("notes", "")

    def test_not_checked_has_no_notes(self):
        scored = _make_scored(num_segs=2)
        query = _make_query()
        result = export_itinerary(scored, query)
        body = "\n".join(line for line in result.splitlines() if not line.startswith("#"))
        data = yaml.safe_load(body)
        for seg in data["segments"]:
            assert "notes" not in seg or "availability" not in seg.get("notes", "")
