"""YAML export for search results."""

from __future__ import annotations

from datetime import date, timedelta
from typing import Optional

import yaml

from rtw.search.models import AvailabilityStatus, ScoredCandidate, SearchQuery


def _assign_export_dates(
    candidate: ScoredCandidate,
    query: SearchQuery,
) -> list[Optional[date]]:
    """Assign dates for export: 3 days between stopovers, same-day transits."""
    segments = candidate.candidate.itinerary.segments
    dates: list[Optional[date]] = []
    current = query.date_from

    for seg in segments:
        if seg.is_surface:
            dates.append(None)
        elif seg.type.value == "transit":
            dates.append(current)
        else:
            dates.append(current)
            current = min(current + timedelta(days=3), query.date_to)

    return dates


def export_itinerary(
    scored: ScoredCandidate,
    query: SearchQuery,
) -> str:
    """Export a scored candidate as YAML string.

    The output is loadable by Itinerary(**yaml.safe_load(output)).
    """
    itin = scored.candidate.itinerary
    dates = _assign_export_dates(scored, query)
    route_segs = scored.candidate.route_segments

    # Build YAML structure
    segments_data = []
    for i, seg in enumerate(itin.segments):
        entry: dict = {
            "from": seg.from_airport,
            "to": seg.to_airport,
            "carrier": seg.carrier,
            "type": seg.type.value,
        }

        # Add date if available
        seg_date = dates[i] if i < len(dates) else None
        if seg_date:
            entry["date"] = seg_date.isoformat()

        # Add availability note
        if i < len(route_segs) and route_segs[i].availability:
            avail = route_segs[i].availability
            if avail.status != AvailabilityStatus.NOT_CHECKED:
                notes = f"availability: {avail.status.value}"
                if avail.price_usd:
                    notes += f" (${avail.price_usd:,.0f})"
                entry["notes"] = notes

        segments_data.append(entry)

    data = {
        "ticket": {
            "type": itin.ticket.type.value,
            "cabin": itin.ticket.cabin.value,
            "origin": itin.ticket.origin,
            "passengers": itin.ticket.passengers,
            "plating_carrier": "AA",
        },
        "segments": segments_data,
    }

    # Build YAML with header comment
    header = (
        f"# Generated by: rtw search\n"
        f"# Direction: {scored.candidate.direction.value}\n"
        f"# Score: {scored.composite_score:.1f}/100\n"
        f"# Rank: #{scored.rank}\n"
        f"# Cities: {', '.join(query.cities)}\n"
        f"# Date range: {query.date_from} to {query.date_to}\n"
    )

    fc = scored.fare_comparison
    if fc is not None and fc.base_fare_usd > 0:
        header += f"# RTW Fare: ${fc.base_fare_usd:,.0f} ({query.origin}/{query.ticket_type.value})\n"
        if fc.segments_priced > 0:
            incomplete = " (incomplete)" if not fc.is_complete else ""
            header += (
                f"# Segment Total: ${fc.segment_total_usd:,.0f} "
                f"({fc.segments_priced}/{fc.segments_total} priced){incomplete}\n"
                f"# Savings: ${fc.savings_usd:,.0f} ({fc.value_multiplier:.1f}x value)\n"
            )

    yaml_body = yaml.dump(data, default_flow_style=False, sort_keys=False)

    return header + yaml_body
